# Generated by Django 3.2.1 on 2021-10-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('lir', 'Local Internet Registry'), ('personal', 'Personal')], default='personal', max_length=9),
        ),
    ]
