# Generated by Django 3.2.1 on 2021-12-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0002_ipupdates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IpUpdates',
        ),
    ]
