# Generated by Django 3.2.1 on 2021-12-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0009_auto_20211209_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iptable',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ipupdates',
            name='created_at',
        ),
    ]
