# Generated by Django 3.2.1 on 2021-12-09 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0010_auto_20211209_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 1, 18, 4, 20, 116981)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipupdates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 12, 1, 18, 4, 28, 181156)),
            preserve_default=False,
        ),
    ]
