# Generated by Django 3.2.1 on 2021-12-11 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0011_auto_20211209_1804'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='iptable',
            name='blacklist_i_ip_addr_ad774d_idx',
        ),
        migrations.RenameField(
            model_name='iptable',
            old_name='check_datetime',
            new_name='last_checked_at',
        ),
        migrations.AddField(
            model_name='iptable',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='iptable',
            index=models.Index(fields=['ip_addr'], name='blacklist_i_ip_addr_423c0d_idx'),
        ),
    ]
